Add map_public_ip_on_launch variable
cloudposse/terraform-aws-named-subnets pull request #23
Opened 2020-10-17 08:44 UTC by alexjurkiewicz

## what
* Support `map_public_ip_on_launch` for public subnets

## why
* This is most useful when deploying public subnets with `nat_enabled = false`

2020-10-18 17:21 UTC, Gowiem requested changes

2020-10-18 17:21 UTC, Gowiem commented on variables.tf
> +variable "map_public_ip_on_launch" {
@alexjurkiewicz we have a common practice of postfixing boolean values with `_enabled`. Can you make this variable `map_public_ip_on_launch_enabled`?

2020-10-18 17:28 UTC, Gowiem commented on variables.tf
> +variable "map_public_ip_on_launch" {
@alexjurkiewicz also make sure to run `make init && make readme` after making this change.

2020-10-18 21:36 UTC, alexjurkiewicz commented
Thanks for the advice about README updating. I've extended this variable to work for both public & private subnets. The use-cases for private subnets with public IPs are pretty niche (self-managed network gateways, other?) but they do exist, and it was a special case to not support this anyway.

2020-10-19 01:04 UTC, Gowiem commented
/test all

2020-10-19 01:19 UTC, Gowiem commented
@alexjurkiewicz Ah sorry to do it to you after already asking for changes, but I can also ask you to add separate variables for private vs public subnets? I worry that if folks go to enable this, they won't expect it to take effect on their private subnets, which could in turn create a security issue for them.

2020-10-19 01:35 UTC, alexjurkiewicz commented
Since this module can only create public or private subnets (not both at the same time), what sort of scenario are you thinking of where people could enable this accidentally on private subnets?

I'm guessing you're thinking of some scenario with `for_each`. But it doesn't seem to be that tricky of a thing to deal with:
```hcl
module "subnets" {
  for_each = toset(["public", "private"])
  source            = "git::https://github.com/cloudposse/terraform-aws-named-subnets.git?ref=master"
  # other params skipped
  type              = each.key
  map_public_ip_on_launch = each.key == "public"
}
```

You would be performing similar logic for other params like `igw_id`/`ngw_id`, `cidr_block`, etc.

2020-10-19 02:07 UTC, Gowiem commented
@alexjurkiewicz Solid point! I haven't used this module personally (I typically use [terraform-aws-dynamic-subnets](https://github.com/cloudposse/terraform-aws-dynamic-subnets)), so I didn't know that it was meant to create one set of subnet type or another.

2020-10-19 02:08 UTC, Gowiem approved these changes

2020-10-19 02:08 UTC, merged

2020-10-19 02:09 UTC, Gowiem commented
@alexjurkiewicz 
Thanks for the contribution! Released as [0.8.0](https://github.com/cloudposse/terraform-aws-named-subnets/releases/tag/0.8.0).